name = "hex-number-field-mathlib"
defaultTargets = ["HexNumberFieldMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexNumberField"
git = "https://github.com/leanprover/hex-number-field.git"
rev = "f75c4cb92b73dc053230f7087fa9a8a7f4edd21b"

[[require]]
name = "HexRootsMathlib"
git = "https://github.com/leanprover/hex-roots-mathlib.git"
rev = "a8774c9e1a27e194e3ab8f3cd0761c8c3bdad257"

[[require]]
name = "HexResultantMathlib"
git = "https://github.com/leanprover/hex-resultant-mathlib.git"
rev = "b40bef9d6083c1df635867813fac6c3bc8455a4e"

[[require]]
name = "HexBerlekampZassenhausMathlib"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus-mathlib.git"
rev = "a64dd3e6c11d864be268121845c9705eb230b1fe"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "d4bbb82b87704d3016c6c1d822ae1f77c793958a"

[[require]]
name = "HexPolyZMathlib"
git = "https://github.com/leanprover/hex-poly-z-mathlib.git"
rev = "d9b7ba1f1ef5bc456f9b7467f694b940d5e5200a"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/leanprover/hex-matrix-mathlib.git"
rev = "7c5744ca46a91252712f1c421911e9a2463d5fd6"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexNumberFieldMathlib"
